export const Qoutes = [
    'We become what we think about',
    "People who are crazy enough to think they can change the world, are the ones who do.",
    'Optimism is the one quality more associated with success and happiness than any other.',
    'Happiness is not something readymade. It comes from your own actions.',
    'All our dreams can come true if we have the courage to pursue them.',
    'Success is not final, failure is not fatal: it is the courage to continue that counts.',
    'Believe you can and you’re halfway there',
    'I can’t change the direction of the wind, but I can adjust my sails to always reach my destination',
    'Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new.',
    'It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.',
    'You are never too old to set another goal or to dream a new dream.',
    'We must be willing to let go of the life we planned so as to have the life that is waiting for us.',
    'Everything you’ve ever wanted is on the other side of fear.',
    'You get what you give.',
    'Your life only gets better when you get better.',
    'Happiness is not by chance, but by choice.',
    'Be the change that you wish to see in the world',
    'If I cannot do great things, I can do small things in a great way.',
    'We generate fears while we sit. We overcome them by action.',
    'Today’s accomplishments were yesterday’s impossibilities.',
    'Light tomorrow with today!',
    'Keep your face always toward the sunshine, and shadows will fall behind you',
    'The bad news is time flies. The good news is you’re the pilot.',
    'Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination.',
    'Let us make our future now, and let us make our dreams tomorrow’s reality.',
    'Don’t Let Yesterday Take Up Too Much Of Today.',
    'For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.',
    'We may encounter many defeats but we must not be defeated.',
    'You only live once, but if you do it right, once is enough.',
    'In three words I can sum up everything I’ve learned about life: it goes on',
    'Life is what happens to us while we are making other plans.',
    'I may not have gone where I intended to go, but I think I have ended up where I needed to be',
    'Life isn’t about finding yourself. Life is about creating yourself.',
    'Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.',
    'You are the sum total of everything you’ve ever seen, heard, eaten, smelled, been told, forgot ― it’s all there. Everything influences each of us, and because of that I try to make sure that my experiences are positive.',
    'The best way to get started is to quit talking and begin doing.',
    'Leaders never use the word failure. They look upon setbacks as learning experiences.',
    'There are no limits to what you can accomplish, except the limits you place on your own thinking.',
    'Someone is sitting in the shade today because someone planted a tree a long time ago.',
    'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.',
    'You learn more from failure than from success. Don’t let it stop you. Failure builds character.',
    'If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.',
    'Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneur.',
    'The man who has confidence in himself gains the confidence of others',
    'What you lack in talent can be made up with desire, hustle and giving 110% all the time.',
    'Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality.',
    'I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.',
    'The only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle.',
    'We become what we think about',
]